# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    
    - name: create env file
      working-directory: ./
      run: |
        pwd
        touch .env

        cat .env

    - name: build server files
      working-directory: ./
      run: |
        npm
        npm run build

    - name: zip file
      run: zip -r test.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./test.zip s3://cicd-pratice/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name cicd-test
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name group
        --s3-location bucket=cicd-test,bundleType=zip,key=deploy/test.zip

